name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  hello-world:
    runs-on: runners-arm64-alpha
    steps:
      - run: |
          echo "Hello world"
